"""Text2Audio Studio — FastAPI backend serving the web UI over the TTS pipeline."""
import io
import importlib.util
import os
import re
import shutil
import sys
import threading
import webbrowser
from contextlib import asynccontextmanager

import soundfile as sf
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, Request, UploadFile
from fastapi.responses import FileResponse, Response, StreamingResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from pipeline.synth import Synthesizer, PRESET_VOICES, SAMPLE_RATE
from backend.library import Library, new_id
from backend.jobs import JobManager
from backend.render import render_audiobook, remaster, purge_wavs, retag_audio
from backend.pronunciations import PronunciationStore
from backend.voices import VoiceStore
from pipeline.clone_synth import ClonedSynthesizer
from pipeline.normalize import normalize_text, BUILTIN_PRONUNCIATIONS
from pipeline.ingest import build_book_text
from pipeline.parse import parse_chapters

ROOT = Path(__file__).parent
WEB_DIR = ROOT / "web"
LIBRARY_DIR = os.environ.get("T2A_LIBRARY_DIR", str(ROOT / "library"))

library = Library(LIBRARY_DIR)
PRON_PATH = os.environ.get("T2A_PRON_PATH", os.path.join(os.path.dirname(LIBRARY_DIR), "data", "pronunciations.json"))
pron = PronunciationStore(PRON_PATH)
VOICES_DIR = os.environ.get("T2A_VOICES_DIR", os.path.join(os.path.dirname(LIBRARY_DIR), "voices"))
voices = VoiceStore(VOICES_DIR)
jobs = JobManager()
_render_lock = threading.Lock()      # one GPU render at a time
_maintenance_lock = threading.Lock()

MAX_BOOK_CHARS = 20_000_000
MAX_INGEST_BYTES = 25 * 1024 * 1024
MAX_VOICE_BYTES = 100 * 1024 * 1024


async def _read_upload(upload: UploadFile, limit: int) -> bytes:
    data = bytearray()
    while chunk := await upload.read(min(1024 * 1024, limit + 1 - len(data))):
        data.extend(chunk)
        if len(data) > limit:
            raise HTTPException(status_code=413, detail="upload is too large")
    return bytes(data)

# Library ids are generated by new_id() as 10 lowercase hex chars. Validate any
# id taken from a request before it touches the filesystem (defends rmtree etc.).
_ID_RE = re.compile(r"^[0-9a-f]{6,32}$")


def _check_id(id: str) -> None:
    if not _ID_RE.match(id):
        raise HTTPException(status_code=404, detail="not found")

_ACCENT = {"a": "American", "b": "British"}
_VOICE_LABELS = {"af_heart": "Heart", "af_bella": "Bella", "af_nicole": "Nicole",
                 "af_sarah": "Sarah", "af_sky": "Sky", "am_michael": "Michael",
                 "am_adam": "Adam", "am_echo": "Echo", "am_liam": "Liam",
                 "bf_emma": "Emma", "bf_isabella": "Isabella", "bf_alice": "Alice",
                 "bm_george": "George", "bm_lewis": "Lewis", "bm_daniel": "Daniel"}


class RenderRequest(BaseModel):
    bookText: str = Field(min_length=1, max_length=MAX_BOOK_CHARS)
    voice: str = "af_heart"
    speed: float = Field(default=1.0, ge=0.5, le=1.5, allow_inf_nan=False)
    title: str = Field(default="", max_length=300)
    author: str = Field(default="", max_length=300)
    # NOTE: no client-supplied filesystem path here. A cover would be uploaded as
    # bytes via multipart and validated before saving — never a server-side path.


def voices_payload() -> list[dict]:
    out = []
    for vid, lang in PRESET_VOICES.items():
        out.append({"id": vid, "label": _VOICE_LABELS.get(vid, vid),
                    "accent": _ACCENT.get(lang, lang),
                    "gender": "Female" if vid[1] == "f" else "Male", "kind": "preset"})
    for v in voices.list():
        out.append({"id": v["id"], "label": v["name"], "name": v["name"],
                    "accent": "Cloned", "gender": "", "kind": "cloned"})
    return out


def resolve_synth(voice_id, speed):
    if voice_id in PRESET_VOICES:
        return Synthesizer(voice=voice_id, lang_code=PRESET_VOICES[voice_id], speed=float(speed))
    meta = voices.get(voice_id)
    if meta is None:
        raise KeyError(voice_id)
    return ClonedSynthesizer(voices.ref_path(voice_id), meta.get("refText", ""), float(speed))


SYNTH_FACTORY = resolve_synth


@asynccontextmanager
async def lifespan(app: FastAPI):
    app.state.ffmpeg_ok = shutil.which("ffmpeg") is not None
    if not app.state.ffmpeg_ok:
        print("WARNING: ffmpeg not found on PATH — audio assembly will fail.", file=sys.stderr)
    yield


app = FastAPI(title="Text2Audio Studio", lifespan=lifespan)


@app.get("/api/health")
def health():
    ffmpeg = shutil.which("ffmpeg")
    espeak = shutil.which("espeak-ng") or os.environ.get("PHONEMIZER_ESPEAK_PATH")
    return {"status": "ok", "ffmpeg": bool(ffmpeg), "espeak": bool(espeak),
            "libraryWritable": os.access(LIBRARY_DIR, os.W_OK),
            "voiceCloning": importlib.util.find_spec("f5_tts") is not None,
            "libraryPath": os.path.abspath(LIBRARY_DIR),
            "voicesWritable": os.access(VOICES_DIR, os.W_OK)}


@app.get("/api/voices")
def get_voices():
    return voices_payload()


@app.get("/")
def index():
    return FileResponse(WEB_DIR / "index.html")


@app.post("/api/ingest")
async def ingest(files: list[UploadFile] = File(...)):
    sources = []
    total = 0
    for f in files:
        data = await _read_upload(f, MAX_INGEST_BYTES - total)
        total += len(data)
        raw = data.decode("utf-8", errors="replace")
        sources.append((f.filename or "untitled.txt", raw))
    book_text = build_book_text(sources)
    chapters = parse_chapters(book_text)
    return {
        "bookText": book_text,
        "chapters": [{"index": i, "title": c.title, "chars": len(c.text)}
                     for i, c in enumerate(chapters)],
    }


@app.post("/api/render")
def start_render(req: RenderRequest):
    if req.voice not in PRESET_VOICES and voices.get(req.voice) is None:
        raise HTTPException(status_code=400, detail="unknown voice")
    # Serialize renders: concurrent GPU inference from two threads is unsafe.
    if not _render_lock.acquire(blocking=False):
        raise HTTPException(status_code=409, detail="A render is already in progress")
    job_id = new_id()

    def target(emit):
        try:
            render_audiobook(book_text=req.bookText, voice=req.voice, speed=req.speed,
                             title=req.title, author=req.author, cover_path=None,
                             library=library, job_id=job_id, emit=emit,
                             synth_factory=SYNTH_FACTORY, custom_rules=pron.get_all())
        finally:
            _render_lock.release()

    jobs.submit(job_id, target)
    return {"jobId": job_id}


@app.get("/api/render/{job_id}/stream")
async def render_stream(job_id: str, request: Request):
    _check_id(job_id)
    try:
        after = int(request.headers.get("last-event-id", "0"))
    except ValueError:
        after = 0
    return StreamingResponse(jobs.stream(job_id, request, after=after), media_type="text/event-stream",
                             headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})


@app.get("/api/library")
def library_list():
    return library.list()


@app.get("/api/library/{id}")
def library_detail(id: str):
    _check_id(id)
    m = library.get(id)
    if m is None:
        raise HTTPException(status_code=404, detail="not found")
    return m


@app.get("/api/audio/{id}")
def library_audio(id: str):
    _check_id(id)
    path = library.audio_path(id)
    if not os.path.isfile(path):
        raise HTTPException(status_code=404, detail="no audio")
    return FileResponse(path, media_type="audio/mp4")  # Starlette handles Range -> 206


@app.get("/api/cover/{id}")
def library_cover(id: str):
    _check_id(id)
    p = library.cover_path(id)
    if not p:
        raise HTTPException(status_code=404, detail="no cover")
    return FileResponse(p, media_type="image/jpeg")


class RetagRequest(BaseModel):
    title: str | None = Field(default=None, max_length=300)
    author: str | None = Field(default=None, max_length=300)


class RemasterRequest(BaseModel):
    bitrate: str = Field(default="128k", pattern=r"^(64|80|96|112|128|160|192|256)k$")
    master: bool = True


class PronRule(BaseModel):
    sayAs: str = Field(max_length=300)


class NormalizePreviewRequest(BaseModel):
    text: str = Field(max_length=10_000)


@app.post("/api/library/{id}/retag")
def library_retag(id: str, req: RetagRequest):
    _check_id(id)
    m = library.get(id)
    if m is None:
        raise HTTPException(status_code=404, detail="not found")
    title = req.title if req.title is not None else m.get("title", "")
    author = req.author if req.author is not None else m.get("author", "")
    with _maintenance_lock:
        retag_audio(library, id, title, author)
        m["title"], m["author"] = title, author
        library.save_manifest(id, m)
    return m


@app.delete("/api/library/{id}")
def library_delete(id: str):
    _check_id(id)
    if library.get(id) is None:
        raise HTTPException(status_code=404, detail="not found")
    with _maintenance_lock:
        library.delete(id)
    return {"deleted": id}


class PreviewRequest(BaseModel):
    voice: str = Field(max_length=200)


_PREVIEW_TEXT = "This is a sample of the selected narrator voice."


@app.post("/api/voice-preview")
def voice_preview(req: PreviewRequest):
    if req.voice not in PRESET_VOICES and voices.get(req.voice) is None:
        raise HTTPException(status_code=400, detail="unknown voice")
    if not _render_lock.acquire(blocking=False):
        raise HTTPException(status_code=409, detail="A render is already in progress")
    synth = None
    try:
        synth = SYNTH_FACTORY(req.voice, 1.0)
        if hasattr(synth, "preview"):
            audio = synth.preview(_PREVIEW_TEXT)
        else:
            audio = synth.synth_chunks([_PREVIEW_TEXT])
    finally:
        if synth is not None and hasattr(synth, "close"):
            synth.close()
        _render_lock.release()
    buf = io.BytesIO()
    sf.write(buf, audio, SAMPLE_RATE, format="WAV")
    return Response(content=buf.getvalue(), media_type="audio/wav")


@app.post("/api/library/{id}/remaster")
def library_remaster(id: str, req: RemasterRequest = RemasterRequest()):
    _check_id(id)
    try:
        with _maintenance_lock:
            return remaster(library, id, bitrate=req.bitrate, master=req.master)
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail="not found")
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.post("/api/library/{id}/purge-wav")
def library_purge(id: str):
    _check_id(id)
    try:
        with _maintenance_lock:
            return purge_wavs(library, id)
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail="not found")


@app.get("/api/pronunciations")
def pronunciations_list():
    return {"builtin": BUILTIN_PRONUNCIATIONS, "custom": pron.get_all()}


@app.put("/api/pronunciations/{word}")
def pronunciations_set(word: str, rule: PronRule):
    if not word.strip() or len(word) > 200:
        raise HTTPException(status_code=400, detail="word must be 1-200 characters")
    if not rule.sayAs.strip():
        raise HTTPException(status_code=400, detail="sayAs is required")
    pron.set_rule(word, rule.sayAs.strip())
    return {"custom": pron.get_all()}


@app.delete("/api/pronunciations/{word}")
def pronunciations_remove(word: str):
    pron.remove(word)
    return {"custom": pron.get_all()}


@app.post("/api/normalize-preview")
def normalize_preview(req: NormalizePreviewRequest):
    return {"normalized": normalize_text(req.text, pron.get_all())}


@app.post("/api/voices/clone")
async def voices_clone(name: str = Form(...), audio: UploadFile = File(...),
                       refText: str = Form("")):
    if not name.strip() or len(name.strip()) > 200:
        raise HTTPException(status_code=400, detail="name is required")
    if len(refText) > 10_000:
        raise HTTPException(status_code=400, detail="reference text is too long")
    data = await _read_upload(audio, MAX_VOICE_BYTES)
    if not data:
        raise HTTPException(status_code=400, detail="audio is required")
    ext = os.path.splitext(audio.filename or "")[1] or ".wav"
    try:
        return voices.create(name.strip(), data, ext, refText.strip())
    except (ValueError, FileNotFoundError) as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.delete("/api/voices/{id}")
def voices_delete(id: str):
    if voices.get(id) is None:
        raise HTTPException(status_code=404, detail="not found")
    voices.delete(id)
    return {"deleted": id}


# IMPORTANT: keep this static mount as the LAST route registration in the file.
def _mount_static():
    app.mount("/", StaticFiles(directory=str(WEB_DIR), html=True), name="web")


_mount_static()


def main():
    import uvicorn
    host, port = "127.0.0.1", 8765
    if os.environ.get("T2A_NO_BROWSER") != "1":
        threading.Timer(0.8, lambda: webbrowser.open(f"http://{host}:{port}")).start()
    uvicorn.run(app, host=host, port=port, log_level="info")


if __name__ == "__main__":
    main()
